### ISSUE TITLE
Exception: array index out of bounds

### ISSUE THREAD

**Issue by syanenko** [JossWhittle/Obj2Pov#3]
Getting following exception on file exported from ZBrush ([Torus.zip](https://github.com/JossWhittle/Obj2Pov/files/10695152/Torus.zip)):

```
java.lang.ArrayIndexOutOfBoundsException: 2
        at obj2pov.convert(obj2pov.java:64)
        at obj2pov.<init>(obj2pov.java:16)
        at obj2pov.main(obj2pov.java:10)
```

**Comment by GeorgeMacDonald** [comment]
else if (lineIn.startsWith("f ")) {

In this section of code the program was failing with obj files that use a simpler "f line" format. The files I was
converting looked like this
# Begin list of faces

f 1 2 3 
f 3 2 4 
f 3 4 5 

I hacked  the code to make it work, not a general solution though. All I did was add:


                ArrayList<Vector> defaultNormals = new ArrayList<Vector>();
                ArrayList<Vector> defaultTextures = new ArrayList<Vector>();

                defaultNormals.add(new Vector("0","0","0"));
                defaultTextures.add(new Vector("0","0"));

and then

 else if (lineIn.startsWith("F ")) {
                                String[] s = lineIn.substring(2).split(" ");
                                int v0 = Integer.parseInt(s[0]) - 1;
                                int v1 = Integer.parseInt(s[1]) - 1;
                                int v2 = Integer.parseInt(s[2]) - 1;
                                int n0 = 0; int n1 = 0; int n2 = 0; int t0 = 0; int t1 = 0; int t2 = 0;
                                Triangle t = new Triangle(vertices.get(v0),
                                                                                   vertices.get(v1),
                                                                                   vertices.get(v2),
                                                                                   defaultNormals.get(n0),
                                                                                   defaultNormals.get(n1),
                                                                                   defaultNormals.get(n2),
                                                                                   defaultTextures.get(t0),
                                                                                   defaultTextures.get(t1),
                                                                                   defaultTextures.get(t2));

                                System.out.println(!smooth ? t.toString() : t.getSmooth());
                        }



I manually edited the .obj files to switch the case of the character f to F so this section of code would then run. 

B.t.w. thanks for the program, very useful. I am  using it to make animations on the PI5 with POVRAY:

https://youtu.be/9Pa8Mrh8bNI

**Comment by syanenko** [comment]
> else if (lineIn.startsWith("f ")) {
> 
> In this section of code the program was failing with obj files that use a simpler "f line" format. The files I was converting looked like this
> ...

Thanks for the report - I will fix it soon.
Animation is also nice :).
